name: Week Forecast (168h)

on:
  schedule:
    - cron: "10 20 * * *"   # ~00:10 Asia/Tbilisi (UTC+4). Cron uses UTC.
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: week-forecast
  cancel-in-progress: false

jobs:
  fetch-week-forecast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade requests
      - name: Sanity check secret
        run: |
          [ -n "$GOOGLE_WEATHER_API_SECRET" ] || { echo "❌ Secret missing"; exit 1; }
          echo "✅ Secret present (masked)"
        env:
          GOOGLE_WEATHER_API_SECRET: ${{ secrets.GOOGLE_WEATHER_API_SECRET }}
      - name: Run forecast fetcher (168h)
        env:
          GOOGLE_WEATHER_API_SECRET: ${{ secrets.GOOGLE_WEATHER_API_SECRET }}
        run: python FetchOneWeekForecast.py

      - name: Commit & push (if changed)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            # Add forecast CSVs only (keep commit small)
            if compgen -G "data/WeekPrediction_*.csv" > /dev/null; then
              git add data/WeekPrediction_*.csv
            fi
            git commit -m "Update WeekPrediction CSVs (168h forecast) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
